import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/app/_components/navbar/Navbar";
import Footer from "@/app/_components/footer/Footer";
import { ToastProvider } from "@/components/providers/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}   h-screen   flex flex-col relative min-h-screen bg-cover bg-center`}
        style={{ backgroundImage: 'url("/bg1.jpeg")' }}
      >
        <ToastProvider />
         <div className="top-0 left-0 w-full h-full relative bg-transparent z-10 overflow-auto">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
